Tensor is the mathematical object used to store data in multiple dimensions

In [11]:
import torch
print(torch.__version__)

2.3.1.post100
The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


### check for gpu access with pytorch

In [223]:
torch.cuda.is_available()

False

## Creating tensor

torch.tensor is function, used to create tensor, which is similar to multi-dimension numpy array but optimized for gpu acceleration and auto differentiation

#### Type:-1 Scalar

In [12]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# to find dimensions of a tensor
scalar.dim()

0

In [5]:
# To get tensor back as a python int
# .item only works with scalar
scalar.item()

7

#### Type:-2 Vector

In [6]:
vector = torch.tensor([4,5])
vector.ndim

1

In [7]:
# .shape return the size of each dimension
vector.shape

torch.Size([2])

#### Type:-3 Matrix

In [8]:
MATRIX = torch.tensor([[7,2], [3,5]])
MATRIX.ndim

2

In [9]:
# to get any specific dimension
MATRIX[0]   # return 1st dimension

tensor([7, 2])

#### Type:-3 Tensor

In [10]:
TENSOR = torch.tensor([[[3,2],
                        [4,7],
                        [2,8]]])
TENSOR.shape

torch.Size([1, 3, 2])

### Random Tensors

why random tensors?
because many neural network learn is that they start with tensor fulll of random numbers.

In [19]:
# creating random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1562, 0.4496, 0.2041, 0.6427],
        [0.6884, 0.9833, 0.2167, 0.9074],
        [0.0462, 0.6687, 0.6420, 0.0083]])

In [21]:
# creating random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,4,3)) # height, width, color channel
random_image_size_tensor

tensor([[[0.1650, 0.0494, 0.5364],
         [0.1302, 0.9885, 0.5283],
         [0.6471, 0.1914, 0.8306],
         [0.5303, 0.3582, 0.4482]],

        [[0.5022, 0.3024, 0.8532],
         [0.7110, 0.7376, 0.6559],
         [0.2093, 0.0903, 0.9471],
         [0.4938, 0.7535, 0.4933]],

        [[0.6761, 0.9767, 0.4038],
         [0.1034, 0.4707, 0.3470],
         [0.2577, 0.7350, 0.0449],
         [0.0451, 0.2292, 0.4387]]])

### Zeros and Ones

In [23]:
# creating a tensor full of zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
# creating a tensor full of ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
# using arange
# torch.arange(1,4) this is also work below is more appropreate way
one_to_ten = torch.arange(start=0, end=10, step=2)   # did not include the last number
one_to_ten


tensor([0, 2, 4, 6, 8])

In [37]:
# CREARING TENSORS LIKE
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

### Tensor DataTypes

In [98]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None, # datatype of the tensor
                                              device="cpu",  # cpu or gpu(cuda)
                                              requires_grad=False) # track gradient
float_32_tensor.device

device(type='cpu')

In [53]:
# changing dtype of an existing tensor and storing it in new variable
float_16_tensor = float_32_tensor.type(torch.half) # or torch.float16
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [57]:
int_32_tensor = torch.tensor([3,4,5], dtype=torch.int32)
int_32_tensor

tensor([3, 4, 5], dtype=torch.int32)

### Getting info from tensor

In [58]:
# getting datatype
int_32_tensor.dtype

torch.int32

In [59]:
# getting device
int_32_tensor.device

device(type='cpu')

In [63]:
# getting shape
int_32_tensor.shape

torch.Size([3])

### Tensor operations

#### Addition & subtraction

In [85]:
tensor_1 = torch.tensor([1,2,3])
tensor_2 = torch.tensor([4,5,6])
# adding two tensors
tensor_1 + tensor_2

tensor([5, 7, 9])

In [72]:
# adding a constant to a tensor
tensor_1 + 10

tensor([11, 12, 13])

In [73]:
# subtraction by a constant
tensor_1 - 1

tensor([0, 1, 2])

In [74]:
# subtracting two tensors
tensor_1 - tensor_2

tensor([-3, -3, -3])

#### matrix multiplication

In [75]:
# element wise mul
tensor_1 * tensor_1

tensor([1, 4, 9])

In [89]:
# matrix mul
torch.matmul(tensor_1, tensor_2)

tensor(32)

#### there are two rules that performing matrix multiplication needs to satisfy
1. The `inner dimensions` must match.
* eg:- (3,2) @ (2,3)
2. The resulting matrix has the shape of the `outer dimensions`.
* eg:- `(2,3) @ (3,2)` -> `(2,2)`

In [93]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))   # here inner dimensions are same

tensor([[0.6505, 0.4544, 0.4590],
        [0.5514, 0.3796, 0.3858],
        [0.6653, 0.8275, 0.6877]])

### One of the most common erros in deep learning is `shape error`

In [94]:
# shapes for matrix multipliation
tensor_a = torch.rand(3,4)
tensor_b = torch.rand(4,3)

In [99]:
torch.matmul(tensor_a, tensor_b).shape  # or mm instead of matmul

torch.Size([3, 3])

#### Transpose
A `Transpose` switches the dimensions of a given tensor.
 we can solve the issue of shape error by this.

In [100]:
tensor_c = torch.rand(4,3)

In [108]:
torch.mm(tensor_b, tensor_c.T)   # Transpose tensor_c to do mm

tensor([[0.3939, 0.3757, 0.5589, 0.6901],
        [0.9540, 0.9471, 1.4530, 1.3845],
        [0.6095, 0.6301, 0.6755, 0.4319],
        [0.9851, 0.9975, 1.1531, 0.9554]])

#### Finding min, max, mean, sum, etc(tensor aggregation)

In [127]:
# Finding min
x = torch.tensor([1,4,6,3]) 
torch.min(x)  # or x.min()

torch.int64

In [125]:
# finding max
x.max()

tensor(6)

##### For finding mean dtype should be either float or complex number

In [133]:
# finding mean
torch.mean(x.type(torch.float32))

tensor(3.5000)

In [134]:
# Finding the sum
torch.sum(x), x.sum()

(tensor(14), tensor(14))

#### Finding position of min and max

In [136]:
# Finding position for min value
x.argmin(), torch.argmin(x)

(tensor(0), tensor(0))

In [137]:
# Finding position for max value
x.argmax(), torch.argmax(x)

(tensor(2), tensor(2))

#### Reshaping, stacking, squeezing and unsqueezing tensors
1. `Reshaping` -> reshapes an input tensor to a defined shape.
2. `View` -> Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
3. `Stacking` -> Combine multiple tensors on top of each other (vstack) or side by side (hstack).
4. `Squeeze` -> removes all `1` dimensions from a tensor.
5. `Unsqueeze` -> add a `1` dimension to a target tensor.
6. `Permute` -> Return a view of the input with dimensions permuted (swaped) in a certain way.

In [139]:
# creating a tensor
y = torch.arange(1,10)
y.shape

torch.Size([9])

In [145]:
# Reshaping
y_reshaped = y.reshape(3,3) # its multiplication should bot exceed original size
y_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

##### changing z will change y because view of a tensor shares same memory

In [149]:
# changing view
z = y.view(1,9)
z

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [155]:
# stack tensors on top (stack default works as vstack another type of hstack)
y_stacked = torch.stack([y,y,y], dim=0)
y_stacked

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [161]:
# torch.squeeze() -> remove all single dimension from a tensor
y_reshaped, y_reshaped.squeeze()

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

#### Indexing (selecting data from tensors)

In [167]:
# creating a new tensor
f = torch.arange(1,10).reshape(1,3,3)
f

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [176]:
# indexing on outer dimension
f[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [177]:
# indexing on middle dimension
f[0][0]

tensor([1, 2, 3])

In [186]:
# indexing on most outer dimension
f[0,1,:], f[:,:,1], f[0,0,1], f[:,0,0]  # : for getting all the value of that dimension

(tensor([4, 5, 6]), tensor([[2, 5, 8]]), tensor(2), tensor([1]))

#### Reproducibility (trying to take random out of random)
To reduce the randomness in neural network and pytorch we use `random seed` concept.

In [210]:
rand_tensor_a = torch.rand(3,4)
rand_tensor_b = torch.rand(3,4)
rand_tensor_a, rand_tensor_b
rand_tensor_a == rand_tensor_b

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [219]:
# let's make some random but reproducible tensors
RANDOM_SEED = 42;
torch.manual_seed(RANDOM_SEED)
rand_tensor_c = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
rand_tensor_d = torch.rand(3,4)
rand_tensor_c == rand_tensor_d

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### Setup device agnostic code
divice = "cuda" if torch.cuda.is_available() else "cpu"
device

### Count number of devices
torch.cuda.device_count()